import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import ThemeToggle from "@/components/theme-toggle";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <ThemeToggle/>
            {children}
            <Toaster
              position="bottom-right"
              richColors
              visibleToasts={5}
              theme="dark"
              closeButton
            />
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
